const STORE = [
  {
    id: 0,
    PRODUCTS: [
      {
        COLLECTIONS: [
          {
            id: 1,
            Title: "COMPUTERS",
            desc: "Get up to 40% off",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Avatares%2FCategories%2Fcomputer.png?alt=media&token=f3645104-3089-4cf5-a581-a68c069e588b",
            categogy: "/computers",
          },
          {
            id: 2,
            Title: "HEADSETS",
            desc: "Get up to 40% off",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Avatares%2FCategories%2Fheased.png?alt=media&token=75138bb0-39a3-46e6-8685-775e9d9151fd",
            categogy: "/headsets",
          },
          {
            id: 3,
            Title: "LAPTOPS",
            desc: "Get up to 40% off",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Avatares%2FCategories%2Flapto.png?alt=media&token=007931be-b1db-4112-955b-8652a5486050",
            categogy: "/laptops",
          },
          {
            id: 4,
            Title: "MONITORS",
            desc: "Get up to 40% off",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Avatares%2FCategories%2Fmonitor.png?alt=media&token=9969b9dd-4768-4345-96a6-de0351598470",
            categogy: "/monitors",
          },
          {
            id: 5,
            Title: "KEYBOARDS",
            desc: "Get up to 40% off",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Avatares%2FCategories%2Fkeboard.png?alt=media&token=961d6a85-7aab-451e-be3b-0b34e46daf7e",
            categogy: "/keyboards",
          },
          {
            id: 6,
            Title: "VIDEO CARDS",
            desc: "Get up to 40% off",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Avatares%2FCategories%2Fvc.png?alt=media&token=52dd4d55-a398-480f-ad84-1d5f2c099fb2",
            categogy: "/accessories",
          },
        ],

        CARDS: [
          {
            id: 1,
            name: "Camisa1",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Fcomputer%2F1.png?alt=media&token=23637959-ae5f-40f0-bd7f-dd5ccc23e996",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
          },
          {
            id: 2,
            name: "Camisa2",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Fcomputer%2F2.png?alt=media&token=39be7e85-f83c-4480-a45e-0cb94948067c",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
          },
          {
            id: 3,
            name: "Camisa3",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Fcomputer%2F3.png?alt=media&token=0fd98682-696c-4266-a281-86303888cedc",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
          },
          {
            id: 4,
            name: "Camisa4",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Fcomputer%2F4.png?alt=media&token=0e74fd6b-a8f9-4b36-8346-8b244a5005f4",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
            categogy: "/computers",
          },
          {
            id: 5,
            name: "Camisa5",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Fcomputer%2F5.png?alt=media&token=c99689fa-f96a-4e18-922c-2e4cede824d3",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
            categogy: "/dfsdf",
          },
          {
            id: 6,
            name: "Camisa6",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Fcomputer%2F6.png?alt=media&token=5b57f9ed-6b94-4499-a155-8af0c8c2f6de",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
          },
          {
            id: 7,
            name: "Pants ",
            description: "Red Pants",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Fcomputer%2F1.png?alt=media&token=23637959-ae5f-40f0-bd7f-dd5ccc23e996",
            price: "$45.00",
            priceDesc: "$39.99",
            desc: "50%",
            star: "**",
          },
          {
            id: 8,
            name: "Bluse",
            description: "Bluse new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Fcomputer%2F3.png?alt=media&token=0fd98682-696c-4266-a281-86303888cedc",
            price: "$40.00",
            //priceDesc: "$38.00",
            //desc: "8%",
            star: "*****",
          },
        ],

        COMPUTERS: [
          {
            id: 1,
            name: "Camisa1",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Fcomputer%2F1.png?alt=media&token=23637959-ae5f-40f0-bd7f-dd5ccc23e996",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
          },
          {
            id: 2,
            name: "Camisa2",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Fcomputer%2F2.png?alt=media&token=39be7e85-f83c-4480-a45e-0cb94948067c",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
          },
          {
            id: 3,
            name: "Camisa3",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Fcomputer%2F3.png?alt=media&token=0fd98682-696c-4266-a281-86303888cedc",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
          },
          {
            id: 4,
            name: "Camisa4",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Fcomputer%2F4.png?alt=media&token=0e74fd6b-a8f9-4b36-8346-8b244a5005f4",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
            categogy: "/computers",
          },
          {
            id: 5,
            name: "Camisa5",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Fcomputer%2F5.png?alt=media&token=c99689fa-f96a-4e18-922c-2e4cede824d3",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
            categogy: "/dfsdf",
          },
          {
            id: 6,
            name: "Camisa6",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Fcomputer%2F6.png?alt=media&token=5b57f9ed-6b94-4499-a155-8af0c8c2f6de",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
          },
          {
            id: 7,
            name: "Pants ",
            description: "Red Pants",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Fcomputer%2F1.png?alt=media&token=23637959-ae5f-40f0-bd7f-dd5ccc23e996",
            price: "$45.00",
            priceDesc: "$39.99",
            desc: "50%",
            star: "**",
          },
          {
            id: 8,
            name: "Bluse",
            description: "Bluse new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Fcomputer%2F3.png?alt=media&token=0fd98682-696c-4266-a281-86303888cedc",
            price: "$40.00",
            //priceDesc: "$38.00",
            //desc: "8%",
            star: "*****",
          },
        ],

        HEADSET: [
          {
            id: 1,
            name: "Camisa1",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Fheadset%2F1.png?alt=media&token=92b9f26a-8e67-45bd-b139-92b4cd2b1e34",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
          },
          {
            id: 2,
            name: "Camisa2",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Fheadset%2F2.png?alt=media&token=9703a61a-e1f0-4701-8f32-bd4181e130dd",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
          },
          {
            id: 3,
            name: "Camisa3",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Fheadset%2F3.png?alt=media&token=d9ce5538-7855-4428-954b-2db081903887",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
          },
          {
            id: 4,
            name: "Camisa4",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Fheadset%2F4.png?alt=media&token=4c8d9bd1-4416-46ff-ba9e-6bb8f83dc0bb",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
          },
          {
            id: 5,
            name: "Camisa5",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Fheadset%2F5.png?alt=media&token=0d1d3698-c257-4724-a11e-73b556aaf4fe",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
          },
          {
            id: 6,
            name: "Camisa6",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Fheadset%2F6.png?alt=media&token=7555b53e-6611-47a9-928b-40a0f09c9f02",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
          },
          {
            id: 7,
            name: "Pants ",
            description: "Red Pants",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Fheadset%2F2.png?alt=media&token=9703a61a-e1f0-4701-8f32-bd4181e130dd",
            price: "$45.00",
            priceDesc: "$39.99",
            desc: "50%",
            star: "**",
          },
          {
            id: 8,
            name: "Bluse",
            description: "Bluse new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Fheadset%2F4.png?alt=media&token=4c8d9bd1-4416-46ff-ba9e-6bb8f83dc0bb",
            price: "$40.00",
            //priceDesc: "$38.00",
            //desc: "8%",
            star: "*****",
          },
        ],

        LAPTOPS: [
          {
            id: 1,
            name: "Camisa1",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Flaptop%2F1.png?alt=media&token=ea5023a0-fdca-45db-b7e3-6191c8d2c3db",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
          },
          {
            id: 2,
            name: "Camisa2",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Flaptop%2F2.png?alt=media&token=d5838436-bc31-4417-8489-3a1b1b9059e2",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
          },
          {
            id: 3,
            name: "Camisa3",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Flaptop%2F3.png?alt=media&token=846625df-1194-4c9b-a427-4ac23ca3fc9b",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
          },
          {
            id: 4,
            name: "Camisa4",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Flaptop%2F4.png?alt=media&token=83ade62d-8300-4e1f-9125-27054ed1c1b1",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
            categogy: "/computers",
          },
          {
            id: 5,
            name: "Camisa5",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Flaptop%2F5.png?alt=media&token=8b683a65-8f37-43e4-97ac-e64e9c43163f",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
            categogy: "/dfsdf",
          },
          {
            id: 6,
            name: "Camisa6",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Flaptop%2F6.png?alt=media&token=db2c2342-ef87-44be-98cf-d894781e9468",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
          },
          {
            id: 7,
            name: "Pants ",
            description: "Red Pants",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Flaptop%2F1.png?alt=media&token=ea5023a0-fdca-45db-b7e3-6191c8d2c3db",
            price: "$45.00",
            priceDesc: "$39.99",
            desc: "50%",
            star: "**",
          },
          {
            id: 8,
            name: "Bluse",
            description: "Bluse new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Flaptop%2F2.png?alt=media&token=d5838436-bc31-4417-8489-3a1b1b9059e2",
            price: "$40.00",
            //priceDesc: "$38.00",
            //desc: "8%",
            star: "*****",
          },
        ],

        MONITOR: [
          {
            id: 1,
            name: "Camisa1",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Fmonitors%2F1.png?alt=media&token=254cf56d-9e2a-4d51-b2c0-7038bfec9d20",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
          },
          {
            id: 2,
            name: "Camisa2",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Fmonitors%2F2.png?alt=media&token=b65adf37-32bc-4863-b264-e637aa787661",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
          },
          {
            id: 3,
            name: "Camisa3",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Fmonitors%2F3.png?alt=media&token=3bca5a7f-c99e-446e-a676-a8052dc911b4",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
          },
          {
            id: 4,
            name: "Camisa4",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Fmonitors%2F4.png?alt=media&token=311e3505-6bee-4166-89f4-dd885ab4aefb",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
          },
          {
            id: 5,
            name: "Camisa5",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Fmonitors%2F5.png?alt=media&token=5d735267-3132-4c2b-b560-ff2e702223e4",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
          },
          {
            id: 6,
            name: "Camisa6",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Fmonitors%2F6.png?alt=media&token=76ba3dd7-b73c-4d36-b7f3-e5f1626ff44e",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
          },
          {
            id: 7,
            name: "Pants ",
            description: "Red Pants",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Fmonitors%2F1.png?alt=media&token=254cf56d-9e2a-4d51-b2c0-7038bfec9d20",
            price: "$45.00",
            priceDesc: "$39.99",
            desc: "50%",
            star: "**",
          },
          {
            id: 8,
            name: "Bluse",
            description: "Bluse new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Fmonitors%2F2.png?alt=media&token=b65adf37-32bc-4863-b264-e637aa787661",
            price: "$40.00",
            //priceDesc: "$38.00",
            //desc: "8%",
            star: "*****",
          },
        ],

        KEYBOARDS: [
          {
            id: 1,
            name: "Camisa1",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Fkeyboard%2F1.png?alt=media&token=4a5e67d6-609a-4708-868e-3051b57197e3",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
          },
          {
            id: 2,
            name: "Camisa2",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Fkeyboard%2F2.png?alt=media&token=9db109bc-6a48-45fc-8268-a280e61604b4",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
          },
          {
            id: 3,
            name: "Camisa3",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Fkeyboard%2F3.png?alt=media&token=119c575c-7967-47ee-80fa-999c7ec0b72f",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
          },
          {
            id: 4,
            name: "Camisa4",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Fkeyboard%2F4.png?alt=media&token=0054f5de-126c-4556-9e82-b6e1ad06968c",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
            categogy: "/computers",
          },
          {
            id: 5,
            name: "Camisa5",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Fkeyboard%2F5.png?alt=media&token=976ac6d3-00a6-4a7d-a0d1-e941f03e5338",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
            categogy: "/dfsdf",
          },
          {
            id: 6,
            name: "Camisa6",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Fkeyboard%2F6.png?alt=media&token=1ddd5eeb-ac9b-44f5-be02-1441dcc1aa3b",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
          },
          {
            id: 7,
            name: "Pants ",
            description: "Red Pants",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Fkeyboard%2F2.png?alt=media&token=9db109bc-6a48-45fc-8268-a280e61604b4",
            price: "$45.00",
            priceDesc: "$39.99",
            desc: "50%",
            star: "**",
          },
          {
            id: 8,
            name: "Bluse",
            description: "Bluse new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Fkeyboard%2F1.png?alt=media&token=4a5e67d6-609a-4708-868e-3051b57197e3",
            price: "$40.00",
            //priceDesc: "$38.00",
            //desc: "8%",
            star: "*****",
          },
        ],

        ACCESSORIES: [
          {
            id: 1,
            name: "Camisa1",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Faccessorie%2F1.png?alt=media&token=45c175f2-9d6b-43c1-91ab-dbcc033fe043",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
          },
          {
            id: 2,
            name: "Camisa2",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Faccessorie%2F2.png?alt=media&token=ec5c0b2a-e1cd-48c4-aa09-d7ae6bb995f5",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
          },
          {
            id: 3,
            name: "Camisa3",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Faccessorie%2F3.png?alt=media&token=fb43844f-b54e-4aa7-8529-ad4feccb53e2",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
          },
          {
            id: 4,
            name: "Camisa4",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Faccessorie%2F4.png?alt=media&token=358a9c19-e9ae-4a6d-998d-bef36308ca6e",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
          },
          {
            id: 5,
            name: "Camisa5",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Faccessorie%2F5.png?alt=media&token=4b2937a1-2522-4b12-b0de-1beb12ebbef0",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
          },
          {
            id: 6,
            name: "Camisa6",
            description: "Shirts new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Faccessorie%2F6.png?alt=media&token=1f230dfd-66de-46bd-85a4-7563d4da2359",
            price: "$20.00",
            priceDesc: "$19.00",
            desc: "10%",
            star: "****",
          },
          {
            id: 7,
            name: "Pants ",
            description: "Red Pants",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Faccessorie%2F7.png?alt=media&token=8cc217d2-54e3-4111-a2d2-cd67f530442f",
            price: "$45.00",
            priceDesc: "$39.99",
            desc: "50%",
            star: "**",
          },
          {
            id: 8,
            name: "Bluse",
            description: "Bluse new",
            pic: "https://firebasestorage.googleapis.com/v0/b/imagenes-cd065.appspot.com/o/Ecommers%2Faccessorie%2F8.png?alt=media&token=2b26c59a-0771-4a1e-b755-5f0bfc309a73",
            price: "$40.00",
            //priceDesc: "$38.00",
            //desc: "8%",
            star: "*****",
          },
        ],
      },
    ],
  },
];

let d = STORE[0].PRODUCTS.map((item) => [
  ...item.ACCESSORIES,
  ...item.LAPTOPS,
  ...item.COMPUTERS,
  ...item.HEADSET,
  ...item.KEYBOARDS,
  ...item.MONITOR,
]).reduce((a, b) => a.concat(b), []);

//console.log(STORE[0].PRODUCTS[0].COLLECTIONS);
//console.log(d);

//let ram = Math.floor(Math.random() * d.length);

//console.log(ram);

let id = Date.now();
let array = [
  {
    0: [{ id, nombre: "Camisa1", precio: "5.00" }],
    1: [{ id, nombre: "Camisa2", precio: "10.00" }],
    2: [{ id, nombre: "Camisa3", precio: "15.00" }],
    3: [{ id, nombre: "Camisa4", precio: "20.00" }],
    4: [{ id, nombre: "Camisa4", precio: "25.00" }],
  },
]




const productos1 = {
  id: 0,
  name: "Camisa1",
  description: "Shirts new",
  cant: 1
}

const productos2 = {
  id: 0,
  name: "Camisa2",
  description: "Shirts new",
  
}

const productos3 = {
  id: 0,
  name: "Camisa2",
  description: "Shirts new",
  
}

const  state = [productos1]

const agregar = (state, producto) => {
  if  (state.findIndex((itemOld) => itemOld.id === producto.id ) < 0) {
        return [...state, { ...producto, cant: 1 }]
  } else {
        return state.map(itemOld => itemOld.id === producto.id ? { ...itemOld, cant: itemOld.cant + 1 } : itemOld)
  }
}

const result = agregar(state, productos3)
console.log(result);
